In [1]:
import numpy as np
list1=[1,2,3]

In [3]:
#making array from list
np.array(list1)

array([1, 2, 3])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [20]:
#0 for start 5,for range 100,how many number you want
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
#random numbers from 0,1
np.random.rand(3)

array([0.38855603, 0.94884703, 0.89810541])

In [23]:
np.random.rand(3,5)

array([[0.50467359, 0.42393167, 0.58957852, 0.23956997, 0.75740355],
       [0.02419608, 0.711788  , 0.24968153, 0.40444325, 0.0122704 ],
       [0.08509981, 0.52348087, 0.53677695, 0.598186  , 0.96733015]])

In [26]:
#by that you could get negative integar
np.random.randn(4,3)

array([[ 0.45400852,  1.09145125,  0.59394108],
       [ 1.15546611,  1.21870522, -0.61163458],
       [-0.4068858 , -0.61934934, -0.46104634],
       [ 0.01037668,  0.8886451 ,  1.19310956]])

In [29]:
#start,end and how many number you want
np.random.randint(0,50,10)

array([10, 17, 11, 24, 23, 21,  7, 31,  0, 36])

In [30]:
arr = np.arange(25)

In [33]:
#you make the martix that complete by the elements, if you try to make small or large it should be error
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
print(arr.max())
print(arr.min())
print(arr.mean())

24
0
12.0


In [36]:
#to find index location
arr.argmax()

24

In [37]:
arr.argmin()

0

In [41]:
arr.shape

(25,)

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [45]:
arr.dtype

dtype('int32')

In [47]:
arr[2][2]

12

In [49]:
arr = arr.reshape(25,)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
#start:end:jumps
arr[1:10:2]

array([1, 3, 5, 7, 9])

In [58]:
#to get slice of a arr and if you change values in it it effects the original array because its linked
slice_arr=arr[0:5]

In [59]:
slice_arr[:]=100

In [60]:
slice_arr

array([100, 100, 100, 100, 100])

In [61]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [63]:
#to made a copy of a array and its not effect the original one
arr_copy=arr.copy()

In [64]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [65]:
arr_copy[:]=100

In [66]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [67]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [68]:
arr = arr.reshape(5,5)

In [69]:
#2nd method for 2d array index and mostly used
#row,colume
arr[0,0]

100

In [70]:
arr[1,2]

7

In [71]:
arr

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [80]:
arr[:2,1:]

array([[100, 100, 100, 100],
       [  6,   7,   8,   9]])

In [82]:
arr[2:,1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [85]:
bool_arr=arr>10
bool_arr

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [86]:
#to get only items that are true
arr[bool_arr]

array([100, 100, 100, 100, 100,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24])

In [89]:
#to get only items that are False
arr[bool_arr==False]

array([ 5,  6,  7,  8,  9, 10])

In [90]:
arr[arr>10]

array([100, 100, 100, 100, 100,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24])

In [91]:
arr_2d=np.arange(25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [96]:
#practice
arr_2d[2:4,1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [99]:
#Operations
ar=np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
#to add index to index
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [101]:
ar -ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [102]:
ar * ar

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [103]:
ar + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [104]:
ar*10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [105]:
ar / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [106]:
#numpy only give alert and you get output but other python give error and stop
ar / ar

<ipython-input-106-c5df7a8f2235>:1: RuntimeWarning: invalid value encountered in true_divide
  ar / ar


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [108]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [109]:
np.exp(ar)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [110]:
np.sin(ar)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [111]:
np.cos(ar)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [112]:
np.log(ar)

<ipython-input-112-60780fce04a1>:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [118]:
#exercise
a=np.arange(5)
a[:]=5
a

array([5, 5, 5, 5, 5])